### ISSUE TITLE
[Question] How to provide the secrets BEFORE the first run of CronJob?

### ISSUE THREAD

**Issue by PawelLipski** [nabsul/k8s-ecr-login-renew#20]
As for now, I'm simply using a Helm pre-install/pre-upgrade hook for that purpose: a Pod with an identical `container` template as for the CronJob. This feels suboptimal tho... do you have any suggestions if this can be done differently?

**Comment by nabsul** [comment]
There is an abandoned PR here that integrates with Hashicorp Vault. I didn't feel like the feature belongs in this tool, but you might find some inspiration there: https://github.com/nabsul/k8s-ecr-login-renew/pull/14

But actually, proper secrets management is something I'd really like to do more reading on. So far I haven't seen a good solution. I manually create the AWS secrets with kubectl before deploying the cronjob, as documented here: https://github.com/nabsul/k8s-ecr-login-renew/blob/main/README.md#deploy-aws-access-keys-to-kubernetes

Since these are secrets, I'm not comfortable putting them in any type of code, but in theory you could create the secret in yaml, as an extra step in https://github.com/nabsul/k8s-ecr-login-renew/blob/main/example/service-account.yml for example.

If you're running kubernetes in Azure, they have built in ways to get secrets securely from key vault to AKS. I assume AWS have something similar. I feel like I've heard of an open source way to do this. It's on my to-learn list. If you find it let me know :-)

As for Helm, so far I feel like benefits of using are not worth the additional complexity. I don't have much experience there.

**Comment by PawelLipski** [comment]
Ok, thanks for the comprehensive response :)
